### PR TITLE
Increase splitting

### PR DESCRIPTION
**Pull request by OlivierBondu**
Increase the splitting of wjets jobs (I was running into too much wall time on the grid)

### CODE REVIEW

**Comment by blinkseb** [comment]
I think we need to improve how we handle it. Clearly the same splitting factor for all our analysis is not viable. We should let each analyses specify a kind of_runtime factor_, which will be multiplied to the splitting factor: an analysis running longer will be able to split more.

**Comment by OlivierBondu** [comment]
this would make sense indeed...

in the meantime, PR updated with WJets HT-binned extensions and another file for Benriched samples

**Comment by pieterdavid** [comment]
thanks for fixing this, with the HT binned W+jets sample I exaggerated a bit indeed (I got the impression from the inclusive TT sample that the splitting was a bit on the high side). A "runtime factor" sounds sensible (if we have out a reasonably consistent default splitting for each sample). If we're adding an option anyway, allowing for setting unitsPerJob explicitly when calling runOnGrid.py may also make sense...

**Comment by OlivierBondu** [comment]
This PR still features additional datasets... do you feel I should revert to the original splitting for WJets or can this be merged ?

**Comment by blinkseb** [comment]
Let's see how it goes like this :+1:

**Pull request merged**
