### PR TITLE
Adding DY HT binned samples

### PR DESCRIPTION
**Pull request by OlivierBondu**
to add to the todo list: merge these with the inclusive samples...

I'm digging around for the njets-binned, but the system appears to be down

### CODE REVIEW

**Comment by blinkseb** [comment]
I'm afraid you won't find an easy way to merge them, some are NLO while some are LO ...

Also, can you add `Spring15MiniAODv2` in the output name to avoid any possible confusion with the upcoming Fall15 samples?

**Comment by BrieucF** [comment]
Ok, let's first see what is the statistic left in these samples after pre-selection. If the inclusive DY is not epsilon then we can start scratching our heads.

**Comment by OlivierBondu** [comment]
both are good points :)
PR updated:
- I renamed the samples
- I added the existing LO samples to this json (this way the NLO stay the baseline)

**Comment by blinkseb** [comment]
Thanks a lot :)

**Comment by OlivierBondu** [comment]
to close up on this one: MCM is back up :)
for the njet binned:
- above M-50 is LO
- below M-50 is NLO (I know, I know)
  both are in 76X anyway.... so we don't have to sort out this mess for now !

**Pull request merged**
