### PR TITLE
More VV samples

### PR DESCRIPTION
**Pull request by OlivierBondu**
Hopefully this is all we discussed

I took powheg instead of amcatnlo whenever available

I cross-checked once, but I am re-cross checking a second time now :)

### CODE REVIEW

**Comment by OlivierBondu** [comment]
yup, it seems we now have all VV containing one lepton

**Comment by blinkseb** [comment]
Great, thanks!

**Comment by swertz** [comment]
Did you have a look at corresponding 76X samples? If not I'll take care of it...

**Comment by OlivierBondu** [comment]
not at all :sweat_smile: sorry !

**Pull request merged**
