### PR TITLE
Adding more backgrounds to ZA processing list

### PR DESCRIPTION
**Pull request by OlivierBondu**
Nota Bene: also adding QCD, it's been a long while we did process it for this analysis... So this is just to be run once, and then we will forget about it :smile:

### CODE REVIEW

**Comment by alesaggio** [comment]
Thanks! BTW I remember there was a reason why to use only "TT_powheg_inclusive" and not also the fully leptonic one? Or am I mistaken? I remember @swertz telling me something about it (but I don't remember what!)...

**Comment by swertz** [comment]
The is a (small) contamination from non-fully-leptonic TT events in the selection, hence the inclusive sample is more "correct". Then of course the dileptonic sample has better statistics, so the optimal thing is to use both samples and remove the fully-leptonic part from the inclusive one.

Note: the fully-leptonic sample uses a different tune from the inclusive one, but the difference should be really small. The recommended tune to use in 2016 was the one in the inclusive.

**Comment by alesaggio** [comment]
Ah, there we go, thanks. :) Then we'll keep both

**Comment by OlivierBondu** [comment]
Thanks !

please wait before merging, it seems like QCD dataset names are incorrect since a while, I'll fix them

**Comment by OlivierBondu** [comment]
List of QCD samples updated, actually only one of them was incorrect and only the comments were outdated. I added also a couple of extensions were available

**Review by alesaggio — COMMENTED** [review]
Thanks! We are still missing the ext1 for DY+2J

**Comment by OlivierBondu** [comment]
added!

**Comment by alesaggio** [comment]
Thanks!

**Pull request merged**
